/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BangDiem.frmBangDiem;
import BangDiem.frmTinhDiem;
import GiaoVien.frmGiaoVien;
import Khoa.frmKhoa;
import LopHoc.frmLopHoc;
import MonHoc.frmMonHoc;
import Search.Search;
import SinhVien.frmSinhVien;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.util.Calendar;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {

    public static String nameLogin;
    private Date today = new Date();
    Locale local = new Locale("vi", "VI");
    DateFormat d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
    String date = d.format(today);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setUser();
//        today = new Date();
//        local = new Locale("en", "EN");
//        d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
//        date = d.format(today);

        Timer dongho = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
//                Calendar lich = Calendar.getInstance();
//                int gio = lich.get(Calendar.HOUR);
//                int phut = lich.get(Calendar.MINUTE);
//                int giay = lich.get(Calendar.SECOND);
//                jtfCurrent.setText(" " + gio + " : " + phut + " : " + giay);
            }
        });
        dongho.start();
    }

    private void setUser() {
        nameLogin = frmLogin.nameLogin;
        jlbUser.setText(nameLogin);

        jlbToday.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbInputStudent = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbInputTeacher = new javax.swing.JButton();
        jbInputDiem = new javax.swing.JButton();
        jbClass = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jbtinhdiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbUser = new javax.swing.JLabel();
        jlbToday = new javax.swing.JLabel();
        jtpContent = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmiLogOff = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jmTimKiem = new javax.swing.JMenu();
        jmTacVu = new javax.swing.JMenu();
        jmiNhapSV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiNhapGV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiNhapDiem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiNhapLop = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiMonHoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiNhapKhoa = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÍ SINH VIÊN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jbInputStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInputStudent.setForeground(new java.awt.Color(0, 0, 204));
        jbInputStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jbInputStudent.setText("Nhập Sinh Viên");
        jbInputStudent.setDefaultCapable(false);
        jbInputStudent.setHideActionText(true);
        jbInputStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputStudent.setIconTextGap(10);
        jbInputStudent.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbInputStudent.setPreferredSize(new java.awt.Dimension(151, 33));
        jbInputStudent.setSelected(true);
        jbInputStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputStudentActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(65, 65, 65))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jbInputTeacher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInputTeacher.setForeground(new java.awt.Color(0, 0, 204));
        jbInputTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jbInputTeacher.setText("Nhập Giáo Viên");
        jbInputTeacher.setDefaultCapable(false);
        jbInputTeacher.setHideActionText(true);
        jbInputTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputTeacher.setIconTextGap(10);
        jbInputTeacher.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbInputTeacher.setPreferredSize(new java.awt.Dimension(151, 33));
        jbInputTeacher.setSelected(true);
        jbInputTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputTeacherActionPerformed(evt);
            }
        });

        jbInputDiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInputDiem.setForeground(new java.awt.Color(0, 0, 204));
        jbInputDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jbInputDiem.setText("Nhập Điểm");
        jbInputDiem.setDefaultCapable(false);
        jbInputDiem.setHideActionText(true);
        jbInputDiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputDiem.setIconTextGap(10);
        jbInputDiem.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbInputDiem.setPreferredSize(new java.awt.Dimension(151, 33));
        jbInputDiem.setSelected(true);
        jbInputDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputDiemActionPerformed(evt);
            }
        });

        jbClass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbClass.setForeground(new java.awt.Color(0, 0, 204));
        jbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jbClass.setText("Nhập Lớp");
        jbClass.setDefaultCapable(false);
        jbClass.setHideActionText(true);
        jbClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbClass.setIconTextGap(10);
        jbClass.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbClass.setPreferredSize(new java.awt.Dimension(151, 33));
        jbClass.setSelected(true);
        jbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClassActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jButton5.setText("Nhập Môn Học");
        jButton5.setDefaultCapable(false);
        jButton5.setHideActionText(true);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(10);
        jButton5.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jButton5.setPreferredSize(new java.awt.Dimension(151, 33));
        jButton5.setSelected(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jButton6.setText("Nhập Khoa");
        jButton6.setDefaultCapable(false);
        jButton6.setHideActionText(true);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setIconTextGap(10);
        jButton6.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jButton6.setPreferredSize(new java.awt.Dimension(151, 33));
        jButton6.setSelected(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jbtinhdiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtinhdiem.setForeground(new java.awt.Color(0, 0, 204));
        jbtinhdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jbtinhdiem.setText("Tính Điểm");
        jbtinhdiem.setDefaultCapable(false);
        jbtinhdiem.setHideActionText(true);
        jbtinhdiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtinhdiem.setIconTextGap(10);
        jbtinhdiem.setMargin(new java.awt.Insets(1, 14, 2, 14));
        jbtinhdiem.setPreferredSize(new java.awt.Dimension(151, 33));
        jbtinhdiem.setSelected(true);
        jbtinhdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtinhdiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbInputStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(jbInputTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbInputDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtinhdiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInputStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInputTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInputDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtinhdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("User:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Today:");

        jlbUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbUser.setForeground(new java.awt.Color(255, 0, 0));

        jlbToday.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbToday.setForeground(new java.awt.Color(0, 102, 0));
        jlbToday.setText("Hour");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbToday, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbToday))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jtpContent.setMinimumSize(new java.awt.Dimension(33, 28));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("HƯỚNG DẪN SỬ DỤNG PHẦN MỀM");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Bước 1: Kiểm tra và nhập,sửa,xóa... thông tin Khoa");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Bước 2: Kiểm tra, nhập,sửa,xóa... thông tin Lớp và Giáo Viên");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("Bước 3: Kiểm tra, nhập,sửa,xóa... thông tin Sinh Viên");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Bước 4: Kiểm tra,nhập,sửa,xóa...nhập thông tin Môn Học");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("Bước 5: Kiểm tra,nhập,sửa,xóa... nhập thông tin Điểm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(236, 236, 236))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jtpContent.addTab("Main", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("QUẢN LÍ SINH VIÊN");

        jMenuBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));

        jmHeThong.setBackground(new java.awt.Color(204, 204, 255));
        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Measure.png"))); // NOI18N
        jmHeThong.setText("System            ");
        jmHeThong.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Measure.png"))); // NOI18N

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logoff.png"))); // NOI18N
        jmiLogOff.setText("Log Off");
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiLogOff);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jmiExit.setText(" Exit                     ");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar2.add(jmHeThong);

        jmTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search-icon.png"))); // NOI18N
        jmTimKiem.setText("Search                ");
        jmTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTimKiemMouseClicked(evt);
            }
        });
        jmTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTimKiemActionPerformed(evt);
            }
        });
        jMenuBar2.add(jmTimKiem);

        jmTacVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Folder-Scheduled-Tasks-icon.png"))); // NOI18N
        jmTacVu.setText(" Task                   ");

        jmiNhapSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jmiNhapSV.setText("Input Student ");
        jmiNhapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapSVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapSV);
        jmTacVu.add(jSeparator1);

        jmiNhapGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jmiNhapGV.setText("Input Teacher");
        jmiNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapGVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapGV);
        jmTacVu.add(jSeparator2);

        jmiNhapDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jmiNhapDiem.setText("Input Mark");
        jmiNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapDiemActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapDiem);
        jmTacVu.add(jSeparator3);

        jmiNhapLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jmiNhapLop.setText("Input Class");
        jmiNhapLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapLopActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapLop);
        jmTacVu.add(jSeparator4);

        jmiMonHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jmiMonHoc.setText("Input Subject");
        jmiMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMonHocActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiMonHoc);
        jmTacVu.add(jSeparator5);

        jmiNhapKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ListMenuPatient1.png"))); // NOI18N
        jmiNhapKhoa.setText("Input Faculty");
        jmiNhapKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapKhoaActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapKhoa);
        jmTacVu.add(jSeparator6);

        jMenuBar2.add(jmTacVu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtpContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtpContent.getAccessibleContext().setAccessibleName("Main");

        setSize(new java.awt.Dimension(1074, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiNhapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapSVActionPerformed
        // TODO add your handling code here:
        frmSinhVien sinhVien = new frmSinhVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Sinh Viên", sinhVien);


    }//GEN-LAST:event_jmiNhapSVActionPerformed

    private void jmiNhapKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapKhoaActionPerformed
        frmKhoa khoa = new frmKhoa();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Khoa", khoa);
    }//GEN-LAST:event_jmiNhapKhoaActionPerformed

    private void jbInputStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputStudentActionPerformed
        frmSinhVien sinhVien = new frmSinhVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Sinh Viên", sinhVien);
    }//GEN-LAST:event_jbInputStudentActionPerformed

    private void jbInputTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputTeacherActionPerformed
        frmGiaoVien giaoVien = new frmGiaoVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Giáo Viên", giaoVien);

    }//GEN-LAST:event_jbInputTeacherActionPerformed

    private void jbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClassActionPerformed
        frmLopHoc lophoc = new frmLopHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Lớp Học", lophoc);
    }//GEN-LAST:event_jbClassActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        frmKhoa khoa = new frmKhoa();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Khoa", khoa);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frmMonHoc monhoc = new frmMonHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Môn Học", monhoc);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jmiNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapGVActionPerformed
        frmGiaoVien giaoVien = new frmGiaoVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Giáo Viên", giaoVien);
    }//GEN-LAST:event_jmiNhapGVActionPerformed

    private void jmiNhapLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapLopActionPerformed
        frmLopHoc lophoc = new frmLopHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Lớp Học", lophoc);
    }//GEN-LAST:event_jmiNhapLopActionPerformed

    private void jmiMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMonHocActionPerformed
        frmMonHoc monhoc = new frmMonHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Môn Học", monhoc);
    }//GEN-LAST:event_jmiMonHocActionPerformed

    private void jbInputDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputDiemActionPerformed
        frmBangDiem bangDiem = new frmBangDiem();
        jtpContent.removeAll();
        jtpContent.add("Bảng Điểm", bangDiem);
    }//GEN-LAST:event_jbInputDiemActionPerformed

    private void jmiNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapDiemActionPerformed
        frmBangDiem bangDiem = new frmBangDiem();
        jtpContent.removeAll();
        jtpContent.add("Bảng Điểm", bangDiem);
    }//GEN-LAST:event_jmiNhapDiemActionPerformed

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        dispose();
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTimKiemActionPerformed
        Search timkiem = new Search();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
    }//GEN-LAST:event_jmTimKiemActionPerformed

    private void jmTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTimKiemMouseClicked
        Search timkiem = new Search();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
    }//GEN-LAST:event_jmTimKiemMouseClicked

    private void jbtinhdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtinhdiemActionPerformed
        frmTinhDiem tinhDiem = new frmTinhDiem();
        jtpContent.removeAll();
        jtpContent.add("Tính Điểm",tinhDiem);
    }//GEN-LAST:event_jbtinhdiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JButton jbClass;
    private javax.swing.JButton jbInputDiem;
    private javax.swing.JButton jbInputStudent;
    private javax.swing.JButton jbInputTeacher;
    private javax.swing.JButton jbtinhdiem;
    private javax.swing.JLabel jlbToday;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenu jmTacVu;
    private javax.swing.JMenu jmTimKiem;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JMenuItem jmiMonHoc;
    private javax.swing.JMenuItem jmiNhapDiem;
    private javax.swing.JMenuItem jmiNhapGV;
    private javax.swing.JMenuItem jmiNhapKhoa;
    private javax.swing.JMenuItem jmiNhapLop;
    private javax.swing.JMenuItem jmiNhapSV;
    private javax.swing.JTabbedPane jtpContent;
    // End of variables declaration//GEN-END:variables
}
